apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  namespace: webserver
  labels:
    app: webserver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - name: webserver
        image: 183538325842.dkr.ecr.ap-southeast-1.amazonaws.com/webserver1:latest
        ports:
        - name: http
          containerPort: 80
        imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: webserver-loadbalancer
  namespace: webserver
spec:
  type: LoadBalancer
  selector:
    app: webserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
